export const projects = [
  {
    status: "detailed",
    id: "jurisroots",
    title: "JurisRoots — Legal Services Portal",
    category: "Engineering",
    industry: "Legal Services",
    location: "Delhi NCR",
    roles: ["Founder", "SEO Strategist", "React Developer", "WordPress Developer", "Backend Developer", "UI Designer", "Performance Optimizer"],
    story: [
      "The objective was to build a modern legal services platform focusing on Court Marriage Registration and Marriage Registration services across Delhi NCR.",
      "Initially the project was developed completely using React, FastAPI, MongoDB, JWT Authentication, an Admin Dashboard, and Role Based Access Control.",
      "Later a second production version was developed in WordPress to improve content management and SEO scalability.",
    ],
    responsibilities: [
      "UI Design", "UX", "Responsive Development", "React", "FastAPI", "MongoDB", "JWT",
      "Admin Dashboard", "Role Based Authentication", "Technical SEO", "Schema",
      "Google Search Console", "Google Analytics", "Sitemap", "Robots", "Keyword Research",
      "Competitor Analysis", "Internal Linking", "Content Architecture", "Core Web Vitals",
      "Performance Optimization",
    ],
    seoKeywords: [
      "Marriage Registration", "Court Marriage Registration", "Marriage Registration Delhi",
      "Marriage Registration Certificate", "Marriage Registration Office Near Me",
      "Special Marriage Act", "Court Marriage Fees Delhi", "Online Court Marriage Delhi",
    ],
    challenges: [
      "Building a scalable legal platform", "Managing SEO architecture", "Fast loading",
      "Large service pages", "Mobile responsiveness", "Security",
    ],
    results: [
      "Professional legal platform", "Complete SEO foundation", "Optimized architecture",
      "Improved user experience", "Future roadmap ready",
    ],
    techStack: ["React", "FastAPI", "MongoDB", "WordPress", "Tailwind", "Vercel", "GA4", "GSC", "Schema.org"],
    github: "https://github.com/wasifjhojha-boop/jurisroots",
    demo: "https://jurisroots.vercel.app",
    image: "/projects/jurisroots.jpg",
  },
  {
    status: "detailed",
    id: "muqeem-brothers",
    title: "Muqeem & Brothers — Export Business Growth",
    category: "Marketing",
    industry: "Export Business",
    location: "Noida",
    roles: ["Digital Marketing Executive", "Google Ads Manager", "Meta Ads Manager", "SEO"],
    story: [
      "Ran performance marketing for an export business across four separate websites — Google Ads, Meta Ads, and SEO managed as one coordinated growth engine rather than four disconnected accounts, as part of a full-time role from Feb 2024 to Feb 2025.",
      "Work centered on competitor analysis, keyword research, and ongoing campaign optimization across search, video, and social placements, with a focus on decreasing CPC through negative keyword techniques and targeting improvements.",
    ],
    responsibilities: [
      "Managing four websites", "Google Ads", "Meta Ads", "SEO", "Competitor Analysis",
      "Keyword Research", "Campaign Optimization", "Landing Pages", "Bid Optimization",
    ],
    challenges: [
      "Coordinating campaigns and SEO across four separate sites for one business",
      "Keeping cost-per-click efficient across competitive export/B2B keywords",
    ],
    results: [
      "Search campaign: 4.44K clicks, 58.4K impressions, ₹37.67 CPC, ₹167K spend",
      "Second search campaign: 2.16K clicks, 27.5K impressions, ₹18.71 CPC, ₹40.4K spend",
      "Video campaign: 1.94M impressions, 73.5K views",
      "Meta campaign: 74K reach, 266 landing page views, ₹2.62 cost per landing page view",
    ],
    techStack: ["Google Ads", "Meta Ads", "Google Analytics", "Search Console"],
    image: "/projects/muqeem-brothers.svg",
  },
  {
    status: "detailed",
    id: "flowzle",
    title: "Flowzle.com — Shopify E-commerce (Now Closed)",
    category: "Engineering",
    industry: "E-commerce",
    location: "Remote",
    roles: ["Founder", "Shopify Developer", "SEO"],
    story: [
      "Designed and launched a Shopify e-commerce site end to end, including product listings, a payment gateway integration, and on-page SEO.",
      "The store has since been closed, but it stands as a full-cycle e-commerce build — from setup to SEO — done solo.",
    ],
    responsibilities: ["Shopify Setup", "Product Listings", "Payment Gateway Integration", "On-Page SEO"],
    challenges: ["Launching a full store solo, end to end, on a new platform"],
    results: ["Fully functional e-commerce store shipped and run to close"],
    techStack: ["Shopify", "On-Page SEO"],
    image: "/projects/flowzle.svg",
  },
  {
    status: "pending",
    id: "google-sites-business",
    title: "Business Service Websites (2 Projects)",
    category: "WordPress",
    topics: ["Google Sites", "Responsive Design", "Content Structuring", "Basic SEO"],
    image: "/projects/google-sites-business.svg",
  },
  {
    status: "pending",
    id: "scrap-traders",
    title: "Scrap Traders",
    category: "Marketing",
    topics: ["Problem", "Business Goals", "Research", "Wireframes", "Development", "SEO", "Deployment", "Future Plans"],
    image: "/projects/scrap-traders.svg",
  },
  {
    status: "pending",
    id: "lineardial",
    title: "LinearDial — Luxury Watches",
    category: "Engineering",
    topics: ["UI", "Performance", "Maintenance", "Optimization"],
    image: "/projects/lineardial.svg",
  },
  {
    status: "pending",
    id: "ethnic-wear",
    title: "Zawaz Studio — Ethical Wear & Fashion",
    category: "WordPress",
    topics: ["Brand Identity", "Luxury UI", "Responsive Design", "Shopping Experience", "Site Architecture", "Modern Design", "3D Elements"],
    image: "/projects/zawaz-studio.png",
  },
  {
    status: "pending",
    id: "pet-shop",
    title: "Zamzam Pet Shop",
    category: "WordPress",
    topics: ["Minimal Design", "Color Palette", "E-commerce Ready"],
    image: "/projects/pet-shop.svg",
  },
];

export const demoWebsites = [
  "Gym", "Clinic", "Jewelry", "Hijab", "Furniture", "Doctor", "Restaurant", "Repair",
  "TV Repair", "Electrician", "Plumber", "Real Estate", "Dentist", "Salon", "Lawyer",
];
